version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pools
    volumes:
      - pools_pg_data:/bitnami/postgresql
  
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'pools_redis_data:/bitnami/redis/data'
  app:
    build: 
      context: . 
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=development
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pools
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  pools_pg_data:
  pools_redis_data: